CREATE DATABASE sergio_db;
USE sergio_db;

CREATE TABLE tb_usuario (id INT PRIMARY KEY AUTO_INCREMENT,
nome VARCHAR(200), senha VARCHAR(200));

INSERT INTO tb_usuario (nome, senha) VALUES ('admin', 'admin');

CREATE TABLE TB_CURSOS(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(200) NOT NULL,
    TIPO VARCHAR(100) NOT NULL
);

INSERT INTO TB_CURSOS(NOME, TIPO) VALUES('ENGENHARIA DA COMPUTAÇÃO', 'BACHARELADO');
INSERT INTO TB_CURSOS(NOME, TIPO) VALUES('ANÁLISE DE SISTEMAS', 'BACHARELADO');