-- Banco de testes com informações básicas para
-- testar a conectividade entre o programa e o MySQL

-- Cria o banco
CREATE DATABASE BIBLIOTECH;

-- Seleciona o banco que será usado
USE BIBLIOTECH;

-- Cria a tabela e seus respectivos atributos
CREATE TABLE USUARIO (
  USE_ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  
  USE_NICK VARCHAR(30) NOT NULL UNIQUE,  /*USAR NO LOGIN*/
  USE_SENHA VARCHAR(100) NOT NULL,   /*USAR NO LOGIN*/
  USE_TYPE ENUM('ADMIN', 'BIBLIOTECARIO', 'CLIENTE') NOT NULL,   /*USAR NO LOGIN*/
  
  USE_NOME VARCHAR(50) NOT NULL,
  USE_SOBRENOME VARCHAR(50),
  USE_DATANASC DATE,
  USE_EMAIL VARCHAR(100) NOT NULL UNIQUE,
  USE_CRIA DATETIME NOT NULL,
  USE_SEXO ENUM ('MAS', 'FEM', 'OUTRO') 
);

INSERT INTO USUARIO VALUES
  ( NULL, 'Admin', 'Admin', 'ADMIN', 'Bruno', 'Fernades', '1990-02-28', 'bruno@email.com',  NOW(), 'MAS'),
  ( NULL, 'Usuario', 'Admin', 'BIBLIOTECARIO', 'Sergio', 'Beltrão', '1990-02-28', 'sergio@email.com',  NOW(), 'MAS');
  
  CREATE TABLE FUNCIONARIO (
  FUN_ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  FUN_ENTRADA DATE NOT NULL,
  FUN_SAIDA DATE,
  FUN_SALARIO DECIMAL(10, 2) NOT NULL
);

INSERT INTO FUNCIONARIO  VALUES
  (NULL, '2022-01-15', NULL, 8000.00),
  (NULL, '2021-03-10', NULL, 6000.00);

CREATE TABLE LIVRO ( 
	ID_LIVRO INT PRIMARY KEY AUTO_INCREMENT,
	LIV_NOME_LIVRO VARCHAR (100) NOT NULL,
	LIV_ISBN VARCHAR (100)NOT NULL,
	LIV_ANO_PUBLICACAO DATE, 
	LIV_PAGINA INT NOT NULL,
	LIV_QUANTIDADE INT,
	LIV_CATEGORIA VARCHAR (50)NOT NULL,
	LIV_PRECO DECIMAL (6,2)
);

INSERT INTO LIVRO VALUES(
	NULL, 'O Segredo das Estrelas', '978-1234567890', '1980-10-12', 320, 10,  'Ficção Científica', '180.20');

CREATE TABLE AUTOR(
	ID_AUTOR INT PRIMARY KEY AUTO_INCREMENT,
	AUT_NOME_AUTOR VARCHAR (100)NOT NULL,
	AUT_DATA_NASC DATE,
	AUT_NACIONALIDADE VARCHAR (50) NOT NULL,
	AUT_BIBLIOGRAFIA TEXT,
	AUT_SEXO ENUM ('MASC', 'FEM')
	);
	
INSERT INTO AUTOR ( AUT_NOME_AUTOR, AUT_DATA_NASC, AUT_NACIONALIDADE, AUT_SEXO) 
 VALUES ('Laura Bens', '1997-01-27', 'Brazil', 'FEM' );

CREATE TABLE EDITORA (
	ID_EDITORA  INT PRIMARY KEY AUTO_INCREMENT,
	EDT_NOME_EDITORA  VARCHAR (50) NOT NULL
	);
	
INSERT INTO EDITORA (EDT_NOME_EDITORA) VALUES ('Galáxia Editora');

CREATE TABLE ENDERECO (
  END_ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  END_RUA VARCHAR(150),
  END_NUM INT,
  END_COMP VARCHAR(50),
  END_BAIRRO VARCHAR(100),
  END_CIDADE VARCHAR(100),
  END_UF VARCHAR (2),
  END_PAIS VARCHAR(50),
  END_CEP VARCHAR(10)
);

INSERT INTO ENDERECO VALUES (NULL, 'Dolores', 13, 'APTO', 'Mooca', 'Sao Paulo', 'SP', 'BRASIL', '987321654');
SHOW COLUMNS FROM ENDERECO;
ALTER TABLE ENDERECO MODIFY COLUMN END_UF VARCHAR (2);



-- Cria a tabela e seus respectivos atributos
CREATE TABLE USUARIOS(
USR_ID INT PRIMARY KEY AUTO_INCREMENT,
USR_NOME VARCHAR(20) not null,
USR_SENHA VARCHAR(16) not null
);

-- Insert de usuário
INSERT INTO USUARIOS(USR_NOME, USR_SENHA)
VALUES('admin', 'admin');
INSERT INTO USUARIOS(USR_NOME, USR_SENHA)
VALUES('sergio', 'senha123');
