CREATE DATABASE DB_BiblioTech;

USE DB_BiblioTech;

CREATE TABLE LIVRO ( 
	ID_LIVRO int PRIMARY KEY AUTO_INCREMENT,
	LI_NOME_LIVRO VARCHAR (100) NOT NULL,
	LI_ISBN VARCHAR (100)NOT NULL,
	LI_ANO_PUBLICACAO DATE, 
	LI_PAGINAS INT NOT NULL,
	LI_QUANTIDADE INT,
	LI_CATEGORIA VARCHAR (50)NOT NULL,
	LI_PRECO DECIMAL (6,2)
);

INSERT INTO LIVRO VALUES(
	NULL, 'O Segredo das Estrelas', '978-1234567890', '1980-10-12', 320, 10,  'Ficção Científica', '180.20');
SELECT * FROM LIVRO;

CREATE TABLE AUTOR(
	ID_AUTOR INT PRIMARY KEY AUTO_INCREMENT,
	AT_NOME_AUTOR VARCHAR (100)NOT NULL,
	AT_DATA_NASC DATE,
	AT_NACIONALIDADE VARCHAR (50) NOT NULL,
	AT_BIBLIOGRAFIA TEXT,
	AT_GENERO ENUM ('MASC', 'FEM', 'OUTROS')
	);
	
INSERT INTO AUTOR ( AT_NOME_AUTOR, AT_DATA_NASC, AT_NACIONALIDADE, AT_GENERO) 
VALUES ('Laura Bens', '1997-01-27', 'Brazil', 'FEM' );
SELECT * FROM AUTOR;

CREATE TABLE EDITORA (
	ID_EDITORA  INT PRIMARY KEY AUTO_INCREMENT,
	ED_NOME_EDITORA  VARCHAR (50) NOT NULL,
	ED_TELEFONE VARCHAR (12) NOT NULL,
	ED_ENDERECO VARCHAR (100)NOT NULL
	);
	
SELECT * FROM EDITORA;
INSERT INTO EDITORA (ED_NOME_EDITORA, ED_TELEFONE, ED_ENDERECO) 
VALUES ('Galáxia Editora', '12345678', 'SP, Centro, AV. Paulista');

CREATE TABLE LIVRO_X_AUTOR (
	ID_FORG_AUTOR INT NOT NULL,
    ID_FORG_LIVRO INT NOT NULL,
    PRIMARY KEY PK_LIVRO_X_AUTOR (ID_FORG_AUTOR, ID_FORG_LIVRO)
);

CREATE TABLE LIVRO_X_EDITORA (
	ID_FORG_LIVRO INT NOT NULL,
    ID_FORG_EDITORA INT NOT NULL,
	PRIMARY KEY PK_EDITORA_X_LIVRO (ID_FORG_LIVRO, ID_FORG_EDITORA)
    );
    
ALTER TABLE LIVRO_X_AUTOR ADD CONSTRAINT PK_LIVRO_X_AUTOR FOREIGN KEY (ID_FORG_LIVRO) REFERENCES LIVRO (ID_LIVRO);
ALTER TABLE LIVRO_X_AUTOR ADD CONSTRAINT PK_AUTOR_X_LIVRO FOREIGN KEY (ID_FORG_AUTOR) REFERENCES AUTOR (ID_AUTOR);
ALTER TABLE LIVRO_X_EDITORA ADD CONSTRAINT PK_EDITORA_X_LIVRO FOREIGN KEY (ID_FORG_EDITORA) REFERENCES EDITORA (ID_EDITORA);

