CREATE DATABASE DB_BiblioTech;

USE DB_BiblioTech;

CREATE TABLE LIVRO ( 
	ID_LIVRO int PRIMARY KEY AUTO_INCREMENT,
	LI_NOME_LIVRO VARCHAR (100) NOT NULL,
	LI_ISBN VARCHAR (100)NOT NULL,
	LI_ANO_PUBLICACAO DATE, 
	LI_PAGINAS INT (4)NOT NULL,
	LI_QUANTIDADE INT,
	LI_CATEGORIA VARCHAR (50)NOT NULL,
	LI_PRECO FLOAT (5.2)
);

INSERT INTO LIVRO VALUES(
	NULL, 'O Segredo das Estrelas', '978-1234567890', '1980-10-12', 320, 10,  'Ficção Científica', '180.20');
SELECT * FROM LIVRO;

CREATE TABLE AUTOR(
	ID_AUTOR INT PRIMARY KEY AUTO_INCREMENT,
	AT_NOME_AUTOR VARCHAR (100)NOT NULL,
	AT_DATA_NASC DATE,
	AT_NACIONALIDADE VARCHAR (50) NOT NULL,
	AT_BIBLIOGRAFIA TEXT,
	AT_GENERO ENUM ('MAS', 'FEM', 'OUTROS')
	);
	
INSERT INTO AUTOR ( AT_NOME_AUTOR, AT_DATA_NASC, AT_NACIONALIDADE, AT_GENERO) 
VALUES ('Laura Bens', '1997-01-27', 'Brazil', 'FEM' );
SELECT * FROM AUTOR;

CREATE TABLE EDITORA (
	ID_EDITORA  INT PRIMARY KEY AUTO_INCREMENT,
	ED_NOME_EDITORA  VARCHAR (50) NOT NULL,
	ED_TELEFONE VARCHAR (12) NOT NULL,
	ED_ENDERECO VARCHAR (100)NOT NULL
	);
	
SELECT * FROM EDITORA;
INSERT INTO EDITORA (ED_NOME_EDITORA, ED_TELEFONE, ED_ENDERECO) 
VALUES ('Galáxia Editora', '12345678', 'SP, Centro, AV. Paulista');

/*
ALTER TABLE Editoras ADD CONSTRAINT Livros_X_Editor FOREIGN KEY (ID_FK_Livros) REFERENCES Livros(ID_livros);
ALTER TABLE Autores ADD CONSTRAINT Livros_X_Autor FOREIGN KEY (ID_FK_Livros) REFERENCES Livros(ID_livros);
*/