CREATE DATABASE DB_BiblioTech;

USE DB_BiblioTech;

CREATE TABLE USUARIO (
  USE_ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  USE_NICK VARCHAR(30) NOT NULL UNIQUE,  /* USAR NO LOGIN */
  USE_SENHA VARCHAR(100) NOT NULL,   /* USAR NO LOGIN */
  USE_TYPE ENUM('ADMIN', 'BIBLIOTECARIO', 'CLIENTE') NOT NULL,   /* USAR NO LOGIN */
  USE_NOME VARCHAR(50) NOT NULL,
  USE_SOBRENOME VARCHAR(50),
  USE_DATANASC DATE,
  USE_EMAIL VARCHAR(100) NOT NULL UNIQUE,
  USE_CRIA DATETIME NOT NULL,
  USE_SEXO ENUM ('MASC', 'FEM', 'OUTRO') /* ALTER TABLE USUARIO CHANGE USE_SEXO USE_SEXO ENUM ('MASC', 'FEM', 'OUTRO'); */
  /* USE_CPF CHAR (11) UNIQUE  ATUALIZAR A TABELA ORIGINAL COM ESTE DADO -- ALTER TABLE USUARIO ADD USE_CPF CHAR (11) */
);

INSERT INTO USUARIO VALUES
  ( NULL, 'admin', 'admin', 'ADMIN', 'Bruno', 'Fernades', '1990-02-28', 'bruno@email.com',  NOW(), 'MAS'),
  ( NULL, 'sergio', 'sergio', 'BIBLIOTECARIO', 'Sérgio', 'Beltrão', '1990-02-28', 'sergio@email.com',  NOW(), 'MAS'),
  ( NULL, 'john', 'john', 'CLIENTE', 'Jonatas', 'Sousa', '1990-02-28', 'john@email.com',  NOW(), 'MAS');
  
  /*TABELA DE CHAVES ESTRANGEIRAS DE LIVRO EDITORA */
CREATE TABLE LIVRO_USUARIO ( 
    ID_LIVRO_USUARIO INT PRIMARY KEY AUTO_INCREMENT,
    ID_LIVRO INT NOT NULL, FOREIGN KEY (ID_LIVRO) REFERENCES LIVRO (ID_LIVRO),
    ID_USUARIO INT NOT NULL, FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(USE_ID)
    );

SELECT * FROM USUARIO;
SHOW COLUMNS FROM USUARIO;
ALTER TABLE USUARIO ADD USE_CPF VARCHAR (11);
ALTER TABLE USUARIO DROP COLUMN USE_SEXO;
ALTER TABLE USUARIO ADD USE_SEXO ENUM ('MASC', 'FEM', 'OUTRO');
UPDATE USUARIO SET USE_CPF = '33333333333' WHERE USE_NICK = 'john';
UPDATE USUARIO SET USE_CPF = '22222222222' WHERE USE_NICK = 'sergio';
UPDATE USUARIO SET USE_CPF = '11111111111' WHERE USE_NICK = 'admin';
-- UPDATE USUARIO SET USE_CPF  VALUES ('admim', '11111111111'), ('sergio', '22222222222'), ('john', '33333333333');

CREATE TABLE ENDERECO (
  END_ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  END_RUA VARCHAR(150),
  END_NUM INT,
  END_COMP VARCHAR(50),
  END_BAIRRO VARCHAR(100),
  END_CIDADE VARCHAR(100),
  END_UF VARCHAR (2),
  END_PAIS VARCHAR(50),
  END_CEP VARCHAR(10)
);

INSERT INTO ENDERECO VALUES (NULL, 'Dolores', 13, 'APTO', 'Mooca', 'Sao Paulo', 'SP', 'BRASIL', '987321654');
  
CREATE TABLE TELEFONE (
	TEL_ID INT PRIMARY KEY AUTO_INCREMENT,
	TEL_TIPO ENUM ('RESIDENCIAL', 'COMERCIAL', 'CELULAR')NOT NULL,
	TEL_TELEFONE VARCHAR (12) NOT NULL	
);
  
INSERT INTO TELEFONE VALUES (NULL, 'CELULAR', '11 994545058'), 
(NULL, 'CELULAR', '11 975630714'), (NULL, 'CELULAR', '11 91340-9833');

/*TABELA DE CHAVES ESTRANGEIRAS DE DADOS USUARIOS */
CREATE TABLE DADOS_USUARIOS ( 
    ID_DADOS_USUARIOS INT PRIMARY KEY AUTO_INCREMENT,
    USUARIO_ID INT NOT NULL, FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(USE_ID),
    TELEFONE_ID INT NOT NULL, FOREIGN KEY (TELEFONE_ID) REFERENCES TELEFONE (TEL_ID),
    ENDERECO_ID INT NOT NULL, FOREIGN KEY (ENDERECO_ID) REFERENCES ENDERECO (END_ID)
);

CREATE TABLE FUNCIONARIO (
  FUN_ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  FUN_ENTRADA DATE NOT NULL,
  FUN_SAIDA DATE,
  FUN_SALARIO DECIMAL(10, 2) NOT NULL
);

INSERT INTO FUNCIONARIO  VALUES
  (NULL, '2022-01-15', NULL, 8000.00),
  (NULL, '2021-03-10', NULL, 6000.00);
  

CREATE TABLE LIVRO ( 
	ID_LIVRO INT PRIMARY KEY AUTO_INCREMENT,
	LIV_NOME_LIVRO VARCHAR (100) NOT NULL,
	LIV_ISBN VARCHAR (100)NOT NULL,
	LIV_ANO_PUBLICACAO DATE, 
	LIV_PAGINA INT NOT NULL,
	LIV_QUANTIDADE INT,
	LIV_CATEGORIA VARCHAR (50)NOT NULL,
	LIV_PRECO DECIMAL (6,2)
);

INSERT INTO LIVRO VALUES(
	NULL, 'O Segredo das Estrelas', '978-1234567890', '1980-10-12', 320, 10,  'Ficção Científica', '180.20');

CREATE TABLE AUTOR(
	ID_AUTOR INT PRIMARY KEY AUTO_INCREMENT,
	AUT_NOME_AUTOR VARCHAR (100)NOT NULL,
	AUT_DATA_NASC DATE,
	AUT_NACIONALIDADE VARCHAR (50) NOT NULL,
	AUT_BIBLIOGRAFIA TEXT,
	AUT_SEXO ENUM ('MASC', 'FEM')
);
	
INSERT INTO AUTOR ( AUT_NOME_AUTOR, AUT_DATA_NASC, AUT_NACIONALIDADE, AUT_SEXO) 
 VALUES ('Laura Bens', '1997-01-27', 'Brazil', 'FEM' );

/*TABELA DE CHAVES ESTRANGEIRAS DE DADOS AUTOR */
  CREATE TABLE DADOS_AUTOR ( 
    ID_DADOS_AUTOR INT PRIMARY KEY AUTO_INCREMENT,
    ID_AUTOR INT NOT NULL, FOREIGN KEY (ID_AUTOR) REFERENCES AUTOR (ID_AUTOR),
    TELEFONE_ID INT NOT NULL, FOREIGN KEY (TELEFONE_ID) REFERENCES TELEFONE (TEL_ID),
    ENDERECO_ID INT NOT NULL, FOREIGN KEY (ENDERECO_ID) REFERENCES ENDERECO (END_ID)
);

/*TABELA DE CHAVES ESTRANGEIRAS DE LIVRO AUTOR */
  CREATE TABLE LIVRO_AUTOR ( 
    ID_LIVRO_AUTOR INT PRIMARY KEY AUTO_INCREMENT,
    ID_LIVRO INT NOT NULL, FOREIGN KEY (ID_LIVRO) REFERENCES LIVRO(ID_LIVRO),
    ID_AUTOR INT NOT NULL, FOREIGN KEY (ID_AUTOR) REFERENCES AUTOR(ID_AUTOR)
);


CREATE TABLE EDITORA (
	ID_EDITORA  INT PRIMARY KEY AUTO_INCREMENT,
	EDT_NOME_EDITORA  VARCHAR (50) NOT NULL
	);
	
INSERT INTO EDITORA (EDT_NOME_EDITORA) VALUES ('Galáxia Editora');


/*TABELA DE CHAVES ESTRANGEIRAS DE DADOS EDITORA */
 CREATE TABLE DADOS_EDITORA ( 
    ID_DADOS_EDITORA INT PRIMARY KEY AUTO_INCREMENT,
    ID_EDITORA INT NOT NULL, FOREIGN KEY (ID_EDITORA) REFERENCES EDITORA (ID_EDITORA),
    TELEFONE_ID INT NOT NULL, FOREIGN KEY (TELEFONE_ID) REFERENCES TELEFONE (TEL_ID),
    ENDERECO_ID INT NOT NULL, FOREIGN KEY (ENDERECO_ID) REFERENCES ENDERECO (END_ID)
);

/*TABELA DE CHAVES ESTRANGEIRAS DE LIVRO EDITORA */
  CREATE TABLE LIVRO_EDITORA ( 
    ID_LIVRO_EDITORA INT PRIMARY KEY AUTO_INCREMENT,
    ID_LIVRO INT NOT NULL, FOREIGN KEY (ID_LIVRO) REFERENCES LIVRO(ID_LIVRO),
    ID_EDITORA INT NOT NULL, FOREIGN KEY (ID_EDITORA) REFERENCES EDITORA (ID_EDITORA)
);
SHOW COLUMNS FROM ENDERECO;

-- Na tabela USUARIO, a coluna USE_SENHA é uma senha e deve ser armazenada de forma segura, o uso de uma senha de texto simples não é recomendado.